### ISSUE TITLE
Patch on "user" or "me" get general error or fields not allowed.

### ISSUE THREAD

**Issue by dallinbjohnson** [doronnahum/feathers-mongoose-casl#17]
Feathers-mongoose-casl - backend
Fethers-vuex - state to feathers management.
vueJs/vuex/vuetify - frontend

### Description of the problem: It won't let us Patch the cloned user object.
it keeps giving us fields that can not be patched.  We then tried the same thing with the me object and that just gives us back a general 500 error.
```
...mapState('auth', {user: 'user', auth_payload: 'payload', loadingProfile: 'isFindPending'}),
-------

this.cloneUser = this.user.clone();

-------

updateProfile() {
        this.cloneUser.patch();
}
```

### users.validators.js
```
// feathers-mongoose-casl
// ------------------------
// const Joi = require('feathers-mongoose-casl/lib/src/utils/joi');
// //un comment to copy to your src folder
const {Joi} = require('feathers-mongoose-casl');

const getJoiObject = function (withRequired) {
  const required = withRequired ? 'required' : 'optional';
  return Joi.object({
    password: Joi.string()[required]().meta({dashboard: {hide: 1}}),
    email: Joi.string().email().meta({unique: true, lowercase: true})[required](),
    verifyChanges: Joi.object().meta({dashboard: {hide: 1}}),
    resetToken: Joi.string().allow(null).meta({dashboard: {hide: 1}}),
    isVerified: Joi.boolean().allow(null).meta({dashboard: {doc: {hide: 1}}}),
    verifyToken: Joi.string().allow(null).meta({dashboard: {hide: 1}}),
    facebookId: Joi.string().allow(null).meta({dashboard: {hide: 1}}),
    auth0Id: Joi.string().allow(null).meta({dashboard: {hide: 1}}),
    githubId: Joi.string().allow(null).meta({dashboard: {hide: 1}}),
    googleId: Joi.string().allow(null).meta({dashboard: {hide: 1}}),
    resetExpires: Joi.date().allow(null).meta({dashboard: {hide: 1}}),
    verifyExpires: Joi.date().allow(null).meta({dashboard: {hide: 1}}),
    roles: Joi.array().items(Joi.string().allow(null).allow('')).allow(null),
    name: Joi.string().meta({})[required](),
    names: Joi.array().items(Joi.string().allow(null).allow('')).allow(null).meta({dashboard: {hide: 1}}),
    phone: Joi.object().meta({})[required](),
    description: Joi.string().allow(null).allow('').meta({}),
    avatarColor: Joi.object({
      hue: Joi.number().allow(null),
      alpha: Joi.number().allow(null).max(1),
      hex: Joi.string().allow(null).regex(/^#([a-fA-F0-9]){3}$|[a-fA-F0-9]{6}$/),
      hexa: Joi.string().allow(null).regex(/^#([a-fA-F0-9]){3}$|[a-fA-F0-9]{6}$/),
      hsla: {
        h: Joi.number().allow(null),
        s: Joi.number().allow(null).min(0).max(1),
        l: Joi.number().allow(null).min(0).max(1),
        a: Joi.number().allow(null).min(0).max(1)
      },
      hsva: {
        h: Joi.number().allow(null),
        s: Joi.number().allow(null).min(0).max(100),
        v: Joi.number().allow(null).min(0).max(100),
        a: Joi.number().allow(null).min(0).max(1)
      },
      rgba: {
        r: Joi.number().allow(null),
        g: Joi.number().allow(null),
        b: Joi.number().allow(null),
        a: Joi.number().allow(null).min(0).max(1)
      }
    }).allow(null).meta({}),
    avatars: Joi.object({
      large: Joi.object().allow(null),
      medium: Joi.object().allow(null),
      small: Joi.object().allow(null),
      favicon: Joi.object().allow(null),
    }).allow(null).meta({}),
    dob: Joi.date().allow(null).meta({dashboard: {hide: 1}}),
    gender: Joi.string().allow(null).allow('').meta({dashboard: {hide: 1}}),
    inGroups: Joi.array().items(
      Joi.objectId().meta({
        type: 'ObjectId',
        ref: 'groups',
        displayKey: 'name'
      }).allow(null)).allow(null),
    favorites: Joi.object({
      groups: Joi.array().items(
        Joi.objectId().meta({
          type: 'ObjectId',
          ref: 'groups',
          displayKey: 'name'
        }).allow(null)).allow(null)
    }).allow(null).meta({}),
    bookmarks: Joi.object({
      groups: Joi.array().items(
        Joi.objectId().meta({
          type: 'ObjectId',
          ref: 'groups',
          displayKey: 'name'
        }).allow(null)).allow(null)
    }).allow(null).meta({}),
    requests: Joi.object({
      inbound: Joi.object({
        relationship: Joi.array().items(
          Joi.objectId().meta({
            type: 'ObjectId',
            ref: 'users',
            displayKey: 'email'
          }).allow(null)).allow(null)
      }).allow(null),
      outbound: Joi.object({
        groups: Joi.array().items(
          Joi.objectId().meta({
            type: 'ObjectId',
            ref: 'groups',
            displayKey: 'name'
          }).allow(null)).allow(null)
      }).allow(null),
    }).allow(null).meta({}),
    isActive: Joi.boolean().meta({dashboard: {doc: {hide: 1}}}).default(true),
    addresses: Joi.array().items(Joi.object().allow(null).meta({})).allow(null),
    locationHistory: Joi.array().items(Joi.object().allow(null).meta({})).allow(null),
    createdBy: Joi.objectId().allow(null).meta({
      type: 'ObjectId',
      ref: 'users',
      displayKey: 'email'
    }),
    updatedBy: Joi.objectId().allow(null).meta({
      type: 'ObjectId',
      ref: 'users',
      displayKey: 'email'
    }),
    updates: Joi.array().items(Joi.object().allow(null).meta({})).allow(null),
  });
};

module.exports = getJoiObject;

// const joi2json = require('../../feathers-mongoose-casl/joi2json');

// console.log(joi2json(Joi.object(getJoiObject(true))).properties.rules.items.meta)

```

### users.hooks.js
```
const verifyHooks = require('feathers-authentication-management').hooks;

const commonHooks = require('feathers-hooks-common');
const {
  hashPassword,
  protect
} = require('@feathersjs/authentication-local').hooks;

// feathers-mongoose-casl
// ------------------------
// const notifier = require('../authmanagement/notifier');
// const authenticate = require('../../hooks/authenticate')
// const validateAbilities = require('../../hooks/abilities')
// const validateSchema = require('../../hooks/validateSchema')
// const sanitizedData = require('../../hooks/sanitizedData')
// //un comment to copy to your src folder
const validateSchema = require('feathers-mongoose-casl/lib/src/hooks/validateSchema');
const authenticate = require('feathers-mongoose-casl/lib/src/hooks/authenticate');
const validateAbilities = require('feathers-mongoose-casl/lib/src/hooks/abilities');
const sanitizedData = require('feathers-mongoose-casl/lib/src/hooks/sanitizedData');
const notifier = require('feathers-mongoose-casl/lib/src/services/authmanagement/notifier');

const updatedBy = require('../../hooks/updated-by');

// const rmRestrictedKeys = require('../../hooks/rm_restricted_keys');

module.exports = {
  before: {
    all: [
      authenticate, // Check user token(JWT) and get user from DB, user will be found at hook.params.user
      validateAbilities // Check user abilities (CASL)
    ],
    find: [],
    get: [],
    create: [
      validateSchema,
      commonHooks.iff(
        commonHooks.isProvider('external'),
        commonHooks.discard(
          'isVerified',
          'verifyToken',
          'verifyShortToken',
          'verifyExpires',
          'verifyChanges',
          'resetToken',
          'resetShortToken',
          'resetExpires',
          'roles'
        )
      ),
      (context) => {
        context.params.userRequest = context.data; // We need this to signin a user after signup
      },
      hashPassword('password'),
      verifyHooks.addVerification()
    ],
    update: [
      validateSchema,
      commonHooks.iff(
        commonHooks.isProvider('external'),
        commonHooks.preventChanges(
          true,
          'isVerified',
          'verifyToken',
          'verifyShortToken',
          'verifyExpires',
          'verifyChanges',
          'resetToken',
          'resetShortToken',
          'resetExpires'
        )
      ),
      updatedBy()
    ],
    patch: [
      // rmRestrictedKeys(),
      validateSchema,
      commonHooks.iff(
        commonHooks.isProvider('external'),
        commonHooks.preventChanges(
          true,
          'email',
          'isVerified',
          'verifyToken',
          'verifyShortToken',
          'verifyExpires',
          'verifyChanges',
          'resetToken',
          'resetShortToken',
          'resetExpires'
        )
      ),
      updatedBy()
    ],
    remove: [updatedBy()]
  },

  after: {
    all: [
      sanitizedData,
      // Make sure the password field is never sent to the client
      // Always must be the last hook
      protect('password'), // do not remove
      commonHooks.when(
        commonHooks.isProvider('external')
        // removeUserProtectedFields(),
      )
    ],
    find: [],
    get: [],
    create: [
      async context => {
        const verifyEmailConfig = context.app.get('feathers-mongoose-casl').verifyEmail;
        const applyIsVerifiedEmail =
          verifyEmailConfig && verifyEmailConfig.enabled;
        if (applyIsVerifiedEmail) {
          notifier(context.app).notifier('resendVerifySignup', context.result);
          context.result.verifiedRequired = true;
        } else {
          const user = await context.app.service('users').find({query: {email: context.params.userRequest.email}});
          // eslint-disable-next-line require-atomic-updates
          context.params.user = user.data[0]; // We need this at feathers-mongoose-casl > returnUserOnLogin.js
          const loginUser = await context.app.service('authentication').create({
            email: context.params.userRequest.email,
            password: context.params.userRequest.password,
            strategy: 'local'
          }, context.params);
          // eslint-disable-next-line require-atomic-updates
          context.dispatch = loginUser;
        }
      },
      verifyHooks.removeVerification(),
    ],
    update: [],
    patch: [],
    remove: []
  }
};

```

### client/store/services/users.js
```
import feathersClient, {makeServicePlugin, BaseModel} from '../../feathers-client'

class User extends BaseModel {
  constructor(data, options) {
    super(data, options)
  }

  // Required for $FeathersVuex plugin to work after production transpile.
  static modelName = 'User';

  // Define default properties here
  static instanceDefaults() {
    return {
      email: '',
      name: '',
      names: [],
      phone: {},
      description: null,
      avatarColor: {
        hue: 0,
        alpha: 1,
        hex: "#FF0000",
        hexa: "#FF0000",
        hsla: {
          h: 0,
          s: 1,
          l: 0.5,
          a: 1
        },
        hsva: {
          h: 0,
          s: 100,
          v: 100,
          a: 1
        },
        rgba: {
          r: 255,
          g: 0,
          b: 0,
          a: 1
        }
      },
      avatars: {
        large: {},
        medium: {},
        small: {},
        favicon: {},
      },
      dob: null,
      gender: null,
      inGroups: [],
      favorites: {
        groups: []
      },
      bookmarks: {
        groups: []
      },
      requests: {
        inbound: {
          relationship: []
        },
        outbound: {
          groups: []
        }
      },
      isActive: null,
      addresses: [],
      locationHistory: [],
      createdBy: null,
      updatedBy: null,
      updates: [],
    }
  }
}

const servicePath = 'users';
const servicePlugin = makeServicePlugin({
  Model: User,
  service: feathersClient.service(servicePath),
  servicePath
});

// Setup the client-side Feathers hooks.
feathersClient.service(servicePath).hooks({
  before: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },
  after: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },
  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
});

export default servicePlugin
```

### part of default.json
```
"pickMeReadFields": [
      "_id",
      "email",
      "verifyChanges",
      "resetToken",
      "isVerified",
      "verifyToken",
      "facebookId",
      "auth0Id",
      "githubId",
      "googleId",
      "resetExpires",
      "verifyExpires",
      "roles",
      "name",
      "phone",
      "description",
      "avatarColor",
      "avatars",
      "dob",
      "gender",
      "inGroups",
      "favorites",
      "bookmarks",
      "requests",
      "isActive",
      "addresses",
      "createdBy",
      "updatedBy"
    ],
    "pickMeUpdateFields": [
      "facebookId",
      "auth0Id",
      "githubId",
      "googleId",
      "roles",
      "name",
      "phone",
      "description",
      "avatarColor",
      "avatars",
      "dob",
      "gender",
      "inGroups",
      "favorites",
      "bookmarks",
      "requests",
      "isActive",
      "addresses"
    ],
```

**Comment by dallinbjohnson** [comment]
Rules is getting the same errors as user when I patch.

```
21:14:56 rules::get (server) 60 ms - 1 pending
  feathers-mongoose-casl abilities hook - user allowed { action: 'patch', serviceName: 'rules' } +63ms
  feathers-mongoose-casl sanitizedData hook - start +21s
  feathers-mongoose-casl sanitizedData hook - end +0ms
  feathers-mongoose-casl validateSchema hook - end, validate successfully, service rules +0ms
  feathers-mongoose-casl validateSchema hook - end, validate failed, service rules +0ms
  @feathersjs/errors NotAcceptable(406): "_id" is not allowed. "updatedAt" is not allowed. "createdAt" is not allowed. "__v" is not allowed +34s
  @feathersjs/errors {} +0ms
21:14:56 rules::patch (socketio) 68.7 ms - 0 pending - FAILED before hook.app.error is not a function
  @feathersjs/errors GeneralError(500): server error +1ms
  @feathersjs/errors {} +0ms
  @feathersjs/transport-commons Error in method 'patch' on service 'rules' GeneralError: server error
    at new GeneralError (/Users/brycejohnson/WebstormProjects/familychain/server/node_modules/@feathersjs/errors/lib/index.js:170:17)
    at Object.<anonymous> (/Users/brycejohnson/WebstormProjects/familychain/server/node_modules/feathers-mongoose-casl/lib/src/hooks/errorHandler/errorHandler.js:8:26)
    at /Users/brycejohnson/WebstormProjects/familychain/server/node_modules/@feathersjs/commons/lib/hooks.js:115:46
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  type: 'FeathersError',
  name: 'GeneralError',
  message: 'server error',
  code: 500,
  className: 'general-error',
  data: undefined,
  errors: {}
} +71ms
  socket.io:socket sending ack [{"name":"GeneralError","message":"server error","code":500,"className":"general-error","errors":{}}] +72ms
  socket.io:client writing packet {"id":2,"type":3,"data":[{"name":"GeneralError","message":"server error","code":500,"className":"general-error","errors":{}}],"nsp":"/"} +21s
  socket.io-parser encoding packet {"id":2,"type":3,"data":[{"name":"GeneralError","message":"server error","code":500,"className":"general-error","errors":{}}],"nsp":"/"} +72ms
  socket.io-parser encoded {"id":2,"type":3,"data":[{"name":"GeneralError","message":"server error","code":500,"className":"general-error","errors":{}}],"nsp":"/"} as 32[{"name":"GeneralError","message":"server error","code":500,"className":"general-error","errors":{}}] +0ms
  engine:socket sending packet "message" (32[{"name":"GeneralError","message":"server error","code":500,"className":"general-error","errors":{}}]) +73ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "432[{"name":"GeneralError","message":"server error","code":500,"className":"general-error","errors":{}}]" +73ms
  engine:ws received "2" +4s
  engine:socket packet +4s
  engine:socket got ping +0ms
  engine:socket sending packet "pong" (undefined) +0ms
```

**Comment by doronnahum** [comment]
Hello @dallinbjohnson,
sorry about the delay, I didn't receive notification about your issue,
did you try to update to the last version?

**Comment by dallinbjohnson** [comment]
"feathers-mongoose-casl": "^2.1.6",

**Comment by doronnahum** [comment]
@dallinbjohnson you need to add the fields that you want to allow the client to update tothe 
pickMeUpdateFields array inside the config file
```
  "feathers-mongoose-casl": {
    "pickMeUpdateFields": [
      "firstName",
      "lastName",
      "image"
    ]
}
```
